### ISSUE TITLE
Make mern-cli clone variants of mern project

### ISSUE THREAD

**Issue by somus** [Hashnode/mern-cli#10]
There have been requests to add specific features into mern-starter which is required by few people or not suitable for beginners. So, we are thinking to have mern-cli clone variants of MERN project with those specific features. It can look something like this,

```
mern list
```

can output something like this

```
Available variants
--------------------------
passport-auth - MERN with passport.js
jwt-auth - MERN with JWT auth
redux-saga - MERN with redux-saga
```

You can clone a particular variant using

```
mern newApp passport-auth
```

This is a rough idea, we can further discuss on how to make it possible.

**Comment by somus** [comment]
This is done in 3c661a4a6e14aabaf85a53b8f2d75b6fbe60d6a7.

Available commands in `mern`

```
Usage: main [options] [command]


  Commands:

    init [name]    Initialize a MERN project.
    list           List MERN variants
    search [term]  Search for MERN variant
    info [term]    View details of a MERN variant
    help [cmd]     display help for [cmd]

  Initialize a MERN powered project

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
    -v, --version  check version
```

Available commands in `merng`. It takes the blueprints for the generators from the corresponding MERN project itself. So, various variants of MERN can have their own generators. For reference, review Hashnode/mern-starter@da8a037f65385fc8178320749c8b30f5fbc23508 in `mern-starter`. Following is the output for the `mern-starter` project.

```
Usage: generate [options] <generator> [args]

  Generate components, routes, controllers, models using mern generator

  Options:

    -h, --help  output usage information

Available Generators
____________________

    dumb-s - Generates a dumb react component in shared components
    Usage: dumb-s [component-name]

    dumb-m - Generates a dumb react component in a module directory
    Usage: dumb-m <module-name>/<component-name>

    functional-s - Generates a functional react component in shared components
    Usage: functional-s [component-name]

    functional-m - Generates a functional react component in a module directory
    Usage: functional-m <module-name>/<component-name>

    module - Generates a module including react components, reducer, action, style & express route, controller, model
    Usage: module [module-name]
```

**Comment by JohnyFreeze** [comment]
Not available variants.I have just basic MERN.But no JWT-auth variant.

Thanks for answer
