### ISSUE TITLE
Issue 3.0 with nvm

### ISSUE THREAD

**Issue by CoericK** [Hashnode/mern-cli#11]
I'm know this issue its related to nvm but i would like to know why is this happening with this actual version of mern-cli, i never had this issue before, any solution?
PS: I dont really want to use `sudo npm install -g mern-cli`

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.2.0/bin/node" "/Users/xxx/.nvm/versions/node/v6.2.0/bin/npm" "install" "-g" "mern-cli"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /Users/xxx/.nvm/versions/node/v6.2.0/bin/mern
npm ERR! code EEXIST

npm ERR! Refusing to delete /Users/xxx/.nvm/versions/node/v6.2.0/bin/mern: ../lib/node_modules/mern-cli/bin/init.js symlink target is not controlled by npm /Users/xxx/.nvm/versions/node/v6.2.0
npm ERR! File exists: /Users/xxx/.nvm/versions/node/v6.2.0/bin/mern
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Desktop/react/ToursProject/npm-debug.log

```

**Comment by kandros** [comment]
i had this issue too without nvm, manually deleting the mern folder did the trick,
`rm -rf /Users/xxx/.nvm/versions/node/v6.2.0/bin/mern` in your case

**Comment by CoericK** [comment]
Yeah i had to do the same but i was wondering what this happened to this version and not to previous ones

**Comment by kandros** [comment]
I don't know, but i don't think is nvm related

**Comment by somus** [comment]
You must have installed mern-cli with a different version of node. After you switched your node version, you have to run `nvm reinstall-packages`, then all the packages will be reinstalled for the changed version of node.
