### ISSUE TITLE
Production commands won't work with npm production install

### ISSUE THREAD

**Issue by kuryaki** [Hashnode/mern-cli#14]
after creating a project with the CLI i did an `npm install --production` and then tried a `npm run bs` this is what will be done hosting a project in heroku and it failed because of dependencies, is this happening to someone else?

**Comment by hegelstad** [comment]
+1

**Comment by somus** [comment]
Actually packages in `devDependencies` are required to build your project. You can `heroku config:set NPM_CONFIG_PRODUCTION=false` to make heroku install `devDependencies` also.
