### ISSUE TITLE
-bash: mern: command not found

### ISSUE THREAD

**Issue by Mindgames** [Hashnode/mern-cli#15]
After running npm install -g mern-cli successfully

_-bash: mern: command not found_

What's up with that, am i missing something here?  Looking at instructions i got the feeling it should work by default. 

---- 
Admin & OS X 10.11.6

**Comment by Mindgames** [comment]
It was a local issue with my npm causing the problem. 

_brew prune
npm r -g mern-cli
npm i -g mern-cli_ 

sorted it out in my case.

**Comment by somus** [comment]
Glad you've figured it out.
