### ISSUE TITLE
mern info mern-starter cli-table output truncated

### ISSUE THREAD

**Issue by HellerCommaA** [Hashnode/mern-cli#17]
When running `mern info mern-starter` on OSX (Darwin Kernel Version 15.4.0), the output is truncated down to (direct paste from terminal, excuse the formatting). 
`Adams-MBP:mern-starter adam$ mern info mern-starter
┌─────────────┬─────────────────────────────────────────────────┐
│ Name        │ mern-starter                                    │
├─────────────┼─────────────────────────────────────────────────┤
│ Description │ Default Mern Starter                            │
├─────────────┼─────────────────────────────────────────────────┤
│ Author      │ Hashnode                                        │
├─────────────┼────?Adams-MBP:mern-starter adam$`

It also throws off my Terminal coloring. And moves the cursor to the middle of the term. Not sure if this is systemic, or just something weird I have in my .bash_profile or what. I know there are supposed to be 3 more rows displayed (and more when more projects get added). I have a bugfix (not checked in) on a local fork using https://github.com/flatiron/cliff over cli-table if you want me to submit a PR.

**Comment by somus** [comment]
Nice catch. PR would be great! 👍

**Comment by HellerCommaA** [comment]
It may be worth it raising the issue upstream with cli-table. I think they
have an issue with displaying an array of objects. Cli-table looks a lot
better than the alternatives...

**Comment by mannyhenri** [comment]
We're removing variants for the time being so shouldn't be an issue anymore
