### ISSUE TITLE
Dependancy issue

### ISSUE THREAD

**Issue by custa1200** [Hashnode/mern-cli#18]
When I followed the instructions for MERN-CLI I get the following on OS X 10.11.6

```
├─┬ UNMET PEER DEPENDENCY webpack@2.1.0-beta.20
```

Also it would make sense in the instructions to tell people to install Mongo before the GIt commands rather than after.

**Comment by somus** [comment]
This warning occurs because some of the packages mentioned webpack 1 as peer dependency, but we are using webpack 2.

I'll mention that MongoDB as a requirement in the readme. Thanks for the suggestion.
