### ISSUE TITLE
Why do you not use the react-router?

### ISSUE THREAD

**Issue by Xurma2** [Hashnode/mern-cli#19]

**Comment by gruberjl** [comment]
mern-cli is the command line package to get boilerplates. To start a React project use mern-cli to get the [mern-starter](https://github.com/Hashnode/mern-starter). Mern-Starter has the React code in it. It does use the React Router.

[source](https://github.com/Hashnode/mern-starter/blob/master/package.json#L50)

**Comment by chrischen-melb** [comment]
this issue can be closed as react-router V4 is being used

**Comment by mannyhenri** [comment]
All being worked on! So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter) and we are working on adding the latest version of React-router.
