### ISSUE TITLE
Unforcing global installation of mern-cli

### ISSUE THREAD

**Issue by fibric** [Hashnode/mern-cli#2]
I think we shouldn't force users to install any global package.
The mern-cli should accept '.' as a parameter or a folder name like it is.
When using '.' mern-cli should execute `git init` and `git pull` in the current directory.

Thoughts?

**Comment by somus** [comment]
Now, `mern-cli` does more than initializing a project with `mern-starter`. We have added the ability to clone different variants of MERN project from various repos and also code generation. So, global installation of `mern-cli` is required. The folder name is optional. If the folder name is not mentioned, it will clone it in the current directory.

**Comment by AceTheNinja** [comment]
`mern init` without the folder name is not working. It says 

> Error! Try again
