### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by MarkRabey** [Hashnode/mern-cli#25]
I was wondering if this project is still maintained and developed at all?

**Comment by philwilson** [comment]
I'm guessing a lack of response suggests the answer may be a no. :(

**Comment by MarkRabey** [comment]
Yeah, I suspected that. Too bad. Had promise.

**Comment by mannyhenri** [comment]
Yes we are working on both the CLI tool and the starter project!!! Take a look [here](https://github.com/Hashnode/mern-starter)
