### ISSUE TITLE
Creating a new project UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by smontiu** [Hashnode/mern-cli#26]
Running npm install, we get:

UNMET PEER DEPENDENCY webpack@2.1.0-beta.8
UNMET PEER DEPENDENCY webpack@^1.0.0 || ^2.0.0 || ^3.0.0

**Comment by mannyhenri** [comment]
All being worked on with! So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter)
