### ISSUE TITLE
Babel-plugin-webpack incorrect peer dependency with webpack > 3.0.0

### ISSUE THREAD

**Issue by lsshawn** [Hashnode/mern-cli#27]
I'm getting this error:

`babel-plugin-webpack-loaders@0.9.0" has incorrect peer dependency "webpack@>=1.12.9 <3.0.0". `     

Is there an issue with webpack 3.3?

**Comment by mannyhenri** [comment]
Are you getting this error using mern-cli or on the project generated? So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter)
