### ISSUE TITLE
React 16.0

### ISSUE THREAD

**Issue by sushantshek20** [Hashnode/mern-cli#29]
npm start gives this warning : 

`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

(node:16891) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
`

**Comment by Rogant** [comment]
This repo needs some love!

**Comment by mannyhenri** [comment]
All being worked on with! So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter)
