### ISSUE TITLE
TypeError: cannot read properrty 'map' of undefined 

### ISSUE THREAD

**Issue by Sammy0807** [Hashnode/mern-cli#30]
The mern blog post works the first time after I give the command non run start. But after any changes I get this error. "Localhost" doesn't work to connect to mongodb on my system so I use "127.0.0.1".  And after I do this,  I get the above error,  also in cases where I install any new dpendecy like socket.io or bluebird (mongoclient). Please any suggestions, because I follow the commands as specified in the docs

**Comment by mannyhenri** [comment]
All being worked on with! So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter)
