### ISSUE TITLE
Add code-splitting feature as required

### ISSUE THREAD

**Issue by jamesgeorge007** [Hashnode/mern-cli#38]
``` code-splitting ``` is a great feature that can reduce load timings 
> Lazy loading is a great way to optimize your site, and it does that by splitting your code at logical   breakpoints, and then loading it once the user has done something that requires, or will require, a new block of code.

It is done by webpack behind the scenes, separating them into multiple files.

So the idea basically is to have a separate command in which the user can specify which component to be imported in the code-splitting way within the routes file. If the user specifies a component that doesn't exist he/she should be prompted with a suitable message.

**Comment by mattlubner** [comment]
Hey @jamesgeorge007, thanks for the suggestion! We're currently working towards MERN v3.0.0 (https://github.com/Hashnode/mern-starter/issues/344), but this is something we'd definitely like to implement (not 100% sure if we'd include it in 3.0.0, but if not, then soon thereafter).

Could you close this issue on the mern-cli repo and recreate it against [mern-starter](https://github.com/Hashnode/mern-starter/issues) instead? 🙏

**Comment by jamesgeorge007** [comment]
@mattlubner Sure :+1:
