### ISSUE TITLE
instead of commander.js use vorpal.js

### ISSUE THREAD

**Issue by SOSANA** [Hashnode/mern-cli#9]
HI @mayankchd & @prank7 

Are you open to using vorpal.js? I am currently playing around with this and thought it would be great to use this with mern-cli.

Are you okay with this for future pr?

**Comment by mayankchd** [comment]
👍

**Comment by somus** [comment]
@SOSANA Thanks for the suggestion! `Vorpal.js` looks good. But for now, we are ok with `commander.js` has to provide. Maybe in the future, we will look into changing it.
